# Generated by Django 5.0.6 on 2024-05-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge_challengesubmission_progress_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='answer',
            new_name='test_script',
        ),
    ]
