# Generated by Django 5.0.4 on 2024-05-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_codesnippet_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
        ),
    ]
