# Generated by Django 5.0.6 on 2024-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
