# Generated by Django 5.0.6 on 2024-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_topic_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='example',
            name='is_executable',
            field=models.BooleanField(default=False),
        ),
    ]
