# Generated by Django 5.0.6 on 2024-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_topic_additional_info_example_is_executable'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
