# Generated by Django 5.0.6 on 2024-06-02 07:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quiz'),
        ('api', '0007_example_description'),
    ]

    operations = [
    ]
