# Generated by Django 5.0.4 on 2024-06-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quiz'),
        ('api', '0007_example_description'),
    ]

    operations = [
    ]
