# Generated by Django 5.0.4 on 2024-06-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_challenge_title'),
        ('api', '0008_merge_0004_quiz_0007_example_description'),
    ]

    operations = [
    ]
