# Generated by Django 5.0.6 on 2024-06-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20240607_0052'),
        ('api', '0010_alter_challenge_title_usedtoken_delete_quiz'),
    ]

    operations = [
    ]
