# Generated by Django 5.0.4 on 2024-06-12 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20240607_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='finished_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
